spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/explore}
    username: ${SPRING_DATASOURCE_USERNAME:explore}
    password: ${SPRING_DATASOURCE_PASSWORD:fitiz-explore}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
server:
  port: 8972


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8710/eureka/}

